### ISSUE TITLE
sollen wir in den namen, also GLUON_RELEASE, irgendwo noch CTF mit rein nehmen?

### ISSUE THREAD

**Issue by spralexx** [chaostreff-flensburg/foerdefunk-site#2]
ich bin für GLUON_RELEASE=CTF-stable-2014.4.0

**Comment by flemming-pr** [comment]
ja bin ich für gestern hatten wir die idee mit cffl =chaosfunkflensburg können wir ja als site code setzen

**Comment by flemming-pr** [comment]
ist ja unsere site conf auch

**Comment by spralexx** [comment]
jor. find cih gut :)

**Comment by roikiermedia** [comment]
+1
